Module: LambdaSharp.LambdaPerformance
Using:
  - Module: LambdaSharp.S3.IO:0.8@lambdasharp
Items:

  - Function: MeasureFunction
    Memory: 512
    Timeout: 900

  - Resource: FunctionPermissions
    Value: !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:LambdaPerformance-*"
    Allow:
      - lambda:CreateFunction
      - lambda:UpdateFunctionConfiguration
      - lambda:DeleteFunction
      - lambda:InvokeFunction

  - Resource: FunctionLogPermissions
    Value: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/LambdaPerformance-*"
    Allow:
      - logs:DeleteLogGroup

  - Package: Projects
    Files: ../../Projects

  - Group: CodeBuild
    Items:

      - Resource: Project
        Type: AWS::CodeBuild::Project
        Properties:
          Artifacts:
            Packaging: NONE
            Type: S3
            Location: !Ref CodeBuild::ArtifactBucket
          Environment:
            ComputeType: BUILD_GENERAL1_SMALL
            Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
            Type: LINUX_CONTAINER
          ServiceRole: !GetAtt CodeBuild::Role.Arn
          Source:
            Type: S3
            Location: !Sub "${Deployment::BucketName}/${Projects}"

      - Resource: Role
        Scope: MeasureFunction
        Type: AWS::IAM::Role
        Properties:
          Description: IAM Role for CodeBuild used by LambdaSharp.LambdaPerformance
          AssumeRolePolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Principal:
                    Service: codebuild.amazonaws.com
                  Action: sts:AssumeRole
          Policies:
            - PolicyName: CodeBuildPolicy
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                      - logs:CreateLogGroup
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                    Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
                  - Effect: Allow
                    Action:
                      - s3:GetBucketAcl
                      - s3:GetBucketLocation
                      - s3:GetObject
                      - s3:GetObjectVersion
                      - s3:ListBucket
                    Resource:
                      - !Sub "arn:${AWS::Partition}:s3:::${Deployment::BucketName}"
                      - !Sub "arn:${AWS::Partition}:s3:::${Deployment::BucketName}/*"
                  - Effect: Allow
                    Action:
                      - s3:PutObject
                    Resource:
                      - !Sub "arn:${AWS::Partition}:s3:::${CodeBuild::ArtifactBucket}"
                      - !Sub "arn:${AWS::Partition}:s3:::${CodeBuild::ArtifactBucket}/*"
                  - Effect: Allow
                    Action:
                      - codebuild:CreateReportGroup
                      - codebuild:CreateReport
                      - codebuild:UpdateReport
                      - codebuild:BatchPutTestCases
                      - codebuild:BatchPutCodeCoverages
                    Resource: !Sub "arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/CodeBuild-*"

      - Resource: ArtifactBucket
        Type: AWS::S3::Bucket

      - Resource: EmptyArtifactBucket
        Scope: MeasureFunction
        Type: LambdaSharp::S3::EmptyBucket
        Properties:
          Bucket: !Ref CodeBuild::ArtifactBucket
