Module: LambdaSharp.LambdaPerformance
Using:
  - Module: LambdaSharp.S3.IO:0.8@lambdasharp
Items:

  - Function: MeasureFunction
    Memory: 512
    Timeout: 900

  - Resource: FunctionPermissions
    Value: !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:LambdaPerformance-*
    Allow:
      - lambda:CreateFunction
      - lambda:UpdateFunctionConfiguration
      - lambda:DeleteFunction
      - lambda:InvokeFunction

  - Resource: FunctionLogPermissions
    Value: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/LambdaPerformance-*
    Allow:
      - logs:DeleteLogGroup

  - Package: Projects
    Files: ../../Projects

  - Group: CodeBuild
    Items:

      - Resource: Project
        Type: AWS::CodeBuild::Project
        Properties:
          Artifacts:
            Type: S3
            Packaging: NONE
            Location: !Ref CodeBuild::ArtifactBucket
          Environment:
            ComputeType: BUILD_GENERAL1_SMALL
            Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
            Type: LINUX_CONTAINER
          ServiceRole: !GetAtt CodeBuild::Role.Arn
          Source:
            Type: S3
            Location: !Sub ${Deployment::BucketName}/${Projects}

      - Resource: Role
        Scope: MeasureFunction
        Type: AWS::IAM::Role
        Properties:
          Description: IAM Role for CodeBuild used by LambdaSharp.LambdaPerformance
          AssumeRolePolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    Service: codebuild.amazonaws.com
                  Action: sts:AssumeRole
          Policies:
            - PolicyName: CodeBuildPolicy
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - logs:CreateLogGroup
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                    Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
                  - Effect: Allow
                    Action:
                      - s3:GetBucketAcl
                      - s3:GetBucketLocation
                      - s3:GetObject
                      - s3:GetObjectVersion
                      - s3:ListBucket
                    Resource:
                      - !Sub arn:${AWS::Partition}:s3:::${Deployment::BucketName}
                      - !Sub arn:${AWS::Partition}:s3:::${Deployment::BucketName}/*
                  - Effect: Allow
                    Action:
                      - s3:PutObject
                    Resource:
                      - !Sub arn:${AWS::Partition}:s3:::${CodeBuild::ArtifactBucket}
                      - !Sub arn:${AWS::Partition}:s3:::${CodeBuild::ArtifactBucket}/*
                  - Effect: Allow
                    Action:
                      - codebuild:CreateReportGroup
                      - codebuild:CreateReport
                      - codebuild:UpdateReport
                      - codebuild:BatchPutTestCases
                      - codebuild:BatchPutCodeCoverages
                    Resource: !Sub arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/CodeBuild-*

      - Resource: ArtifactBucket
        Scope: MeasureFunction
        Type: AWS::S3::Bucket

      - Resource: EmptyArtifactBucket
        Type: LambdaSharp::S3::EmptyBucket
        Properties:
          Bucket: !Ref CodeBuild::ArtifactBucket

  - Resource: RunStepFunction
    Pragmas:
      - no-type-validation # needed because `Definition` is defined as an empty object
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineType: STANDARD
      RoleArn: !GetAtt StepFunctionRole.Arn
      Definition:
        StartAt: StartBuild
        States:
          StartBuild:
            Type: Task
            Resource: !Sub arn:${AWS::Partition}:states:::codebuild:startBuild.sync
            Parameters:
              ProjectName: !Ref CodeBuild::Project
            Next: GetBuildResults

          GetBuildResults:
            Type: Choice
            Choices:
              - Variable: $.Reports[0].Status
                StringEquals: SUCCEEDED
                Next: BuildSuccess
            Default: BuildFailed

          BuildSuccess:
            Type: Succeed

          BuildFailed:
            Type: Fail

  - Resource: StepFunctionRole
    Type: AWS::IAM::Role
    Properties:
      Description: IAM Role for CodeBuild used by LambdaSharp.LambdaPerformance
      AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: !Sub states.${AWS::Region}.amazonaws.com
              Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                Resource: !Sub arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:project/${CodeBuild::Project}
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt MeasureFunction.Arn
              - Effect: Allow
                Action:
                  - events:PutTargets
                  - events:PutRule
                  - events:DescribeRule
                Resource:
                  - !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/*

